import Head from "next/head";
import styles from '@styles/applayout.module.sass'
import BottomBar from "@/components/BottomBar";
import Sidebar from "@/components/Sidebar";
import { useState } from 'react'

export default function AppLayout({children, setParticles, particles}: any){
  const [openSettings, setOpenSettings] = useState(0)

  return(
    <>
      <Head>
        <title>Minesweeper Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.background}/>
      <div className={styles.content}>
        <Sidebar
          setOpenSettings={setOpenSettings}
          openSettings={openSettings}
          setParticles={setParticles}
          particles={particles}/>
        {children}
        <BottomBar
          setOpenSettings={setOpenSettings}
          openSettings={openSettings}/>
      </div>
    </>
  )
}